language: c
compiler: gcc
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
before_install: sudo apt-get update -qq
install: sudo apt-get install -y gcc-avr avr-libc binutils-avr
before_script: 
script: cd Firmware/Chameleon-Mini/; make
deploy:
  provider: releases
  api_key: $GH_API_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/Firmware/Chameleon-Mini/Chameleon-Mini.hex"
    - "$TRAVIS_BUILD_DIR/Firmware/Chameleon-Mini/Chameleon-Mini.eep"
  skip_cleanup: true